### PR TITLE
Suggestion or bug report

### LINKED ISSUE #50: Suggest feature page
Cool features:
Checkbox to ask to append a print of the current page.
Checkbox to ask to append the current "link"

### PR DESCRIPTION
**Pull request by thePeras**
Closes #50, #49 and #58 
There is a weird bug when using fetch, but the reports is receveid. 
Maybe its a best decision change the controlled fields values to an actual html form

Screenshot 2023-08-30 at 19 48 35

### CODE REVIEW

**Comment by ttoino** [comment]
What kind of bug?

**Comment by thePeras** [comment]
> What kind of bug?

CORS relative, Can not fetch the resource.
But the forms are sent. I suppose we are not using an official way to do it, so it's normal.

**Comment by LuisDuarte1** [comment]
> CORS relative, Can not fetch the network resource. But the forms are sent. I suppose we are not using an official way to do it, so it's normal.
You should test if this behavior is constant between firefox, chome and safari. Because it seems a bit weird that CORS blocks the request and it's being sent anyways. 

If this applies to all platforms, I can live with it until we get our own solution for thins :thinking:

**Review by ttoino — APPROVED** [review]
Good job! I tested both in firefox and in chromium and it seems to be working in both. Just a minor nitpick, I think the gap between the label and input looks a little bit small.

**Comment by thePeras** [comment]
> 



> Good job! I tested both in firefox and in chromium and it seems to be working in both. Just a minor nitpick, I think the gap between the label and input looks a little bit small.

It's the same space as the home page between title and box. I decided no to change because of inconsistent

**Comment by ttoino** [comment]
> > 
> 
> > Good job! I tested both in firefox and in chromium and it seems to be working in both. Just a minor nitpick, I think the gap between the label and input looks a little bit small.
> 
> It's the same space as the home page between title and box. I decided no to change because of inconsistent

Alright, then I feel this can be safely merged.

**Pull request merged**
