### PR TITLE
Minor changes in homepage design and agenda style

### LINKED ISSUE #5: Change "Agenda" style
Change the css of

Screenshot 2023-02-25 at 09 41 45

### PR DESCRIPTION
**Pull request by lfsjesus**
Closes #5 

Some minor changes in homepage's design:
- changed 'Faculdade de Engenharia da Universidade do Porto' font-family
- removed upper-right corner 'ajuda' link because it's unecessary
- changed hover effect of homepage buttons as suggested in Figma. it's almost indistinguishable (very simple) but i think it fits well, otherwise, it's too much. 
- as proposed in figma, a selected calendar event has now a different background color (it was yellow before), more consistent with the color pallete (closes #5).

calendar
button
news
homepage

### CODE REVIEW

**Comment by thePeras** [comment]
What about to change the agenda style to white theme instead of a black background?
Also, I think the plus icon in the news can be replaced with a button "ler mais".
I think the "Faculdade de Engenharia da Universidade do Porto" steals with a big space between letters...

Besides that, I like the changes

**Comment by lfsjesus** [comment]
> What about to change the agenda style to white theme instead of a black background? Also, I think the plus icon in the news can be replaced with a button "ler mais". I think the "Faculdade de Engenharia da Universidade do Porto" steals with a big space between letters...
> 
> Besides that, I like the changes

I actually prefer this light calendar theme. I also wondered if it'd seem better without the '+' icon, but I like the combination '+ Ler mais'. 

What do you think?
image

**Comment by thePeras** [comment]
About the calendar:
- Yes, the light theme makes the calendar more consistent with the rest of the page.
- Is it also possible to add a margin between 13/14/15/16/17 days? The line connects and hides the function "in this day happens something".
- I notice in the current implementation there are "calendfer" and "calendfds" class names for holidays and weekend days. Maybe you could be playing with that.

About Read More buttons
- I prefer without the icon. The button looks too complex with it.
- It is better to switch to a more neutral color like grey. Red buttons distracts user interaction on the page.
- Make sure to apply the same border radius as other buttons. Also adjust "Filtrar" button.

**Comment by lfsjesus** [comment]
I proceeded to the proposed changes. What do you think (calendar cells seem a bit more narrow but it's because I zoomed out to take the screenshot)?

image

I did not do anything regarding holidays and weekends in the calendar. Still thinking if there's something nice and relevant to do there or not.

**Review by thePeras — APPROVED** [review]

**Pull request merged**
