### PR TITLE
Redesign profile and course information on profile pages

### LINKED ISSUE #114: Redesign Profile Section
Refactor the common section between the following pages (which consists of the profile information and photo, and the course cards):
```js
const profileRowPages = [
    "fest_geral.cursos_list",
    "fest_geral.curso_percurso_academico_view",
    "fest_geral.curso_posicao_plano_view",
    "fest_geral.ucurr_inscricoes_list",
    "fest_geral.estatutos_regimes_view",
    "fest_geral.info_ingresso_view",
    "fest_geral.info_pessoal_completa_view"
];
```

### PR DESCRIPTION
**Pull request by LuisDuarte1**
Closes #114 

This does not only work with own profile information, but with other people information.

image

### CODE REVIEW

**Comment by toni-santos** [comment]
Looks great and works flawlessly for me. Only thing I'd point out is that this link is taking up the entire width of the box, which can lead to opening the link rather than the "box's content".

image

**Comment by LuisDuarte1** [comment]
> Looks great and works flawlessly for me. Only thing I'd point out is that this link is taking up the entire width of the box, which can lead to opening the link rather than the "box's content". This can be easily fixed with `width: fit-content;`.
> 
> image

Nice point! I'll try to fix it ^^ 

The card looks comically wide though, can you send an entire page screenshot, please? I think it's due to `flex-basis: 45%;` being the ideal on my resolution but on larger monitors maybe it stretches out the card, but the screenshot an confirm that ^^

**Comment by toni-santos** [comment]
> > Looks great and works flawlessly for me. Only thing I'd point out is that this link is taking up the entire width of the box, which can lead to opening the link rather than the "box's content". This can be easily fixed with `width: fit-content;`.
> > image
> 
> Nice point! I'll try to fix it ^^
> 
> The card looks comically wide though, can you send an entire page screenshot, please? I think it's due to `flex-basis: 45%;` being the ideal on my resolution but on larger monitors maybe it stretches out the card, but the screenshot can confirm that ^^

Here's the screenshot, to be honest I don't think it looks that bad, I do like the fact that these important parts take up a nice amount of real estate of the page. Regardless, do as you see fit. :)

image

**Comment by LuisDuarte1** [comment]
> Here's the screenshot, to be honest I don't think it looks that bad, I do like the fact that these important parts take up a nice amount of real estate of the page. Regardless, do as you see fit. :)

I'll cc. @ttoino @thePeras wdyt? should we keep as it is? or should we change it to try and make the cards try to fit the content?

**Comment by thePeras** [comment]
> > Here's the screenshot, to be honest I don't think it looks that bad, I do like the fact that these important parts take up a nice amount of real estate of the page. Regardless, do as you see fit. :)
> 
> I'll cc. @ttoino @thePeras wdyt? should we keep as it is? or should we change it to try and make the cards try to fit the content?

I prefer fitting the content

**Comment by ttoino** [comment]
> > Here's the screenshot, to be honest I don't think it looks that bad, I do like the fact that these important parts take up a nice amount of real estate of the page. Regardless, do as you see fit. :)
> 
> I'll cc. @ttoino @thePeras wdyt? should we keep as it is? or should we change it to try and make the cards try to fit the content?

It might look better if it fits to the content. Also, I think the cards should have the same height, I'm sure this can be achieved with some flex box property.

**Comment by LuisDuarte1** [comment]
I've fixed the width of a card, and just in case the `se-course-card-list` container is too small for a card's width, we use container queries to resize the card to fit 100% of the `se-course-card-list` container ^^.

> It might look better if it fits to the content. Also, I think the cards should have the same height, I'm sure this can be achieved with some flex box property.

Should the cards have the same size even though it implies that we might get unwanted extra space at the bottom? I prefer the look of this, but if the majority prefers the height being the same through out the cards, I can change it.

**Comment by ttoino** [comment]
> I've fixed the width of a card, and just in case the `se-course-card-list` container is too small for a card's width, we use container queries to resize the card to fit 100% of the `se-course-card-list` container ^^.
> 
> > It might look better if it fits to the content. Also, I think the cards should have the same height, I'm sure this can be achieved with some flex box property.
> 
> Should the cards have the same size even though it implies that we might get unwanted extra space at the bottom? I prefer the look of this, but if the majority prefers the height being the same through out the cards, I can change it.

IMO the cards being the same height would look the best, and if we align the info to the bottom, then we won't have any weird empty space. Picture for clarity:
image

**Review by ttoino — CHANGES_REQUESTED** [review]
Good job on this PR! The changes are looking really good, but I have some minor improvements that I think would look good:

- This part of the profile page could also be adapted to use cards, maybe different ones since these courses need different information:
  image
- We could replace the @ icon with and actual @ character, this would improve the UX when copying an email. Similarly, we can remove the i icon as it's not working and it's not that useful anyways.
  image
- The up number being a link to your own profile page feels quite redundant, it could look better as a subtitle, like the ones in the course cards.
  image
- This part of the card should not be a table, that is confusing to screen readers.
  image

**Review by ttoino — APPROVED** [review]

**Pull request merged**
