### PR TITLE
Simplify page layout and redesign header

### LINKED ISSUE #3: Navigation top bar
Add a preference to hide the actual navigation left bar and replace it with a new one fully custom by our end at the top of the page.

Estudantes
- Escolher Turma
- Calendário
- (... the most features used from students)

Pesquisa
- Estudantes
- Docentes
- (...)

Serviços
- Ementas (here!?)
- Matrículas (here!?)
- (...)

Faculdade
- (... other options)

### PR DESCRIPTION
**Pull request by ttoino**
Closes #3.

Simplifies the page layout by removing some useless elements and redesigns the header to be cleaner.

image
image

### CODE REVIEW

**Comment by toni-santos** [comment]
In some pages, the right side column has scroll-x being shown even though it has no content that is needed, we should make it hidden.
Example: https://sigarra.up.pt/feup/pt/uni_geral.nivel_list?pv_nivel_id=4

**Comment by toni-santos** [comment]
The links also don't seem to be properly centered on the page, maybe switching to grid instead of flex will help. Other than that it looks really good, especially the login section! Great job :)

**Comment by LuisDuarte1** [comment]
Good work! It looks great,  just with some caveats: 

- When the the login popup opens, the links change position;
- The top bar looks too big on my resolution

image

**Comment by ttoino** [comment]
I also tried out this design for smaller screens, what do you think?

image

**Comment by LuisDuarte1** [comment]
Good job, maybe make use of media queries in order to resize the height of the header because it looks a bit too big on my resolution ^^ :sweat_smile: 
image

**Comment by LuisDuarte1** [comment]
> Good job, maybe make use of media queries in order to resize the height of the header because it looks a bit too big on my resolution ^^ 😅

Maybe it's not because of the height but because of the lack of separation between the content and the header ^^

**Comment by thePeras** [comment]
Make the dropdown closer to the link. Is to distance from the link. Also, I don't think clicking is a good option, hover should open the dropdown, the user is expecting that from another websites.

Without the left navigation, the website content is too closed to left. What about adding more padding?
Also, the navbar can have more padding in horizontal direction.

We should include "Calendário Escolar" in the navigation.

Perfil dropdown: It must exist an explicit option to go to the user profile. (Name and UP number should be only visible information)

**Review by toni-santos — APPROVED** [review]

**Review by LuisDuarte1 — APPROVED** [review]

**Pull request merged**
